#!/bin/bash

# This script demonstrates the email verification system

echo "========================================="
echo "نظام التحقق من البريد الإلكتروني"
echo "Email Verification System Test"
echo "========================================="
echo ""
echo "الخطوات:"
echo "1. افتح التطبيق في http://localhost:3000"
echo "2. اضغط على 'إنشاء حساب' (Register)"
echo "3. أدخل البيانات التالية:"
echo "   - اسم المستخدم: test_user (مثال)"
echo "   - البريد الإلكتروني: test@example.com (مثال)"
echo "   - كلمة المرور: password123 (6+ أحرف)"
echo "   - تأكيد كلمة المرور"
echo ""
echo "4. اضغط زر 'تسجيل'"
echo "5. يجب أن ترى رسالة: 'تم إنشاء الحساب بنجاح! تحقق من بريدك الإلكتروني'"
echo ""
echo "6. افتح DevTools أو شاهد سجلات الخادم (npm run dev)"
echo "   ستجد رسالة مثل:"
echo "   [v0] Verification email to: test@example.com"
echo "   [v0] Verification link: http://localhost:3000/verify-email?token=abc123..."
echo ""
echo "7. انسخ الرابط والصقه في المتصفح"
echo "   أو اضغط عليه مباشرة"
echo ""
echo "8. يجب أن ترى صفحة تحقق تقول:"
echo "   'تم التحقق بنجاح!'"
echo ""
echo "9. سيتم إعادة توجيهك تلقائياً للصفحة الرئيسية"
echo "   وسيكون لديك جلسة نشطة (logged in)"
echo ""
echo "========================================="
echo ""
echo "ملاحظات مهمة:"
echo "- البريد الإلكتروني مطلوب الآن (ليس اختياري)"
echo "- الرمز صالح لمدة 24 ساعة"
echo "- يمكن استخدام نفس البريد مرة واحدة فقط"
echo "- للبيئة الإنتاجية، استخدم Resend أو SendGrid"
echo "  (راجع EMAIL_VERIFICATION.md للتفاصيل)"
echo ""
